##BA WITH R PROJECT CLEAN

Campaigns.df <- read.csv("C:/Users/theme/Downloads/WA_Fn-UseC_-HR-Employee-Attrition.csv")
library(arules)
library(fastDummies)
##preprocessing starts here
min_max_scale <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

campaign.index <- sample(c(1:dim(Campaigns.df)[1]), dim(Campaigns.df)[1]*0.6)  
Campaigns.df$Attrition <- ifelse(Campaigns.df$Attrition == "Yes", 1, 0)
CampaignsCut.df<-Campaigns.df[,c(-9,-22,-27)]

columns_to_scale <- c("Age", "DailyRate", "DistanceFromHome", "HourlyRate", 
                      "MonthlyIncome", "MonthlyRate", "NumCompaniesWorked", 
                      "PercentSalaryHike", "TotalWorkingYears", "YearsAtCompany", 
                      "YearsInCurrentRole", "YearsSinceLastPromotion", 
                      "YearsWithCurrManager")
columns_to_scale <- columns_to_scale[columns_to_scale %in% names(data)]

CampaignsCut.df[columns_to_scale] <- lapply(CampaignsCut.df[columns_to_scale], min_max_scale)

CampaignsCut.df <- fastDummies::dummy_cols(CampaignsCut.df, 
                                           select_columns = c("BusinessTravel", 
                                                              "Department", "EducationField", 
                                                              "Gender", "JobRole", 
                                                              "MaritalStatus", "OverTime"),
                                           remove_selected_columns = TRUE)


CampaignsCut.df$AgeGroup <- cut(CampaignsCut.df$Age, breaks = c(0, 30, 40, 50, 60), 
                                labels = c("20-30", "31-40", "41-50", "51-60"))

CampaignsCut.df<-CampaignsCut.df[,c(-1)]

# Convert columns 26 to 53 from 0/1 to Yes/No
CampaignsCut.df[ , 26:53] <- lapply(CampaignsCut.df[ , 26:53], 
                                    function(x) factor(x, levels = c(1, 0), labels = c("Yes", "No")))
CampaignsCut.df$Attrition <- factor(CampaignsCut.df$Attrition, levels = c(1, 0), labels = c("Yes", "No")) ##transform back

# Identify columns generated by `fastDummies`
dummy_columns <- colnames(CampaignsCut.df)[grepl("_", colnames(CampaignsCut.df))]
# For each original categorical variable, remove one redundant column
columns_to_keep <- dummy_columns[!grepl("_No$", dummy_columns)]  # Keep columns not ending with "_No"
CampaignsCut.df <- CampaignsCut.df[, c(setdiff(names(CampaignsCut.df), dummy_columns), columns_to_keep)]

columns_to_remove <- c(  "BusinessTravel_Non-Travel", "Gender_Male", "OverTime_Yes")
# Drop redundant columns
CampaignsCut.df <- CampaignsCut.df[, !colnames(CampaignsCut.df) %in% columns_to_remove]

summary(CampaignsCut.df)

CampaignsCut.df[] <- lapply(CampaignsCut.df, function(x) {
  if (is.numeric(x)) factor(x) else x
})
Attrition.trans <- as(CampaignsCut.df, "transactions")

attrition_rules <- apriori(Attrition.trans, 
                           parameter = list(supp = 0.01, conf = 0.3, minlen = 2,maxlen=10),
                           appearance = list(rhs = c("Attrition=Yes"), default = "lhs"))

inspect(sort(attrition_rules, by = "lift")[1:10])


columns_to_remove <- grep("JobRole|EducationField/Department", colnames(CampaignsCut.df), value = TRUE)

# Drop these columns from the data frame
CampaignsCut.df <- CampaignsCut.df[, !colnames(CampaignsCut.df) %in% columns_to_remove]
Attrition.trans <- as(CampaignsCut.df, "transactions")


attrition_rules_YN <- apriori(Attrition.trans, 
                              parameter = list(supp = 0.2, conf = 0.6, minlen = 3,maxlen=5),
                              appearance = list(rhs = c("Attrition=Yes", "Attrition=No"), default = "lhs"))
#sorted_rules <- sort(attrition_rules, by = "lift")
inspect(sort(attrition_rules_YN, by = "lift")[1:10])  # View top 10 rules by lift

attrition_rules <- apriori(Attrition.trans, 
                           parameter = list(supp = 0.01, conf = 0.6, minlen = 2,maxlen=10),
                           appearance = list(rhs = c("Attrition=Yes"), default = "lhs"))

inspect(sort(attrition_rules, by = "lift")[1:20])


attrition_rules_YN <- apriori(Attrition.trans, 
                              parameter = list(supp = 0.1, conf = 0.6, minlen = 3,maxlen=5),
                              appearance = list(rhs = c("Attrition=Yes", "Attrition=No"), default = "lhs"))
#sorted_rules <- sort(attrition_rules, by = "lift")
inspect(sort(attrition_rules_YN, by = "lift")[1:10])  # View top 10 rules by lift






#Clustering

d.norm <- dist(CampaignsCut.df, method = "euclidean")
d.norm
hc1 <- hclust(d.norm, method = "ward.D")
plot(hc1, hang = -1, ann = FALSE)
memb <- cutree(hc1, k = 5)
memb

set.seed(2)
km <- kmeans(d.norm, 5)
#set the number to the amount of different clusters we want.
# show cluster membership
km$cluster
km$centers
plot(c(0), xaxt = 'n', ylab = "", type = "l", 
     ylim = c(min(km$centers), max(km$centers)), xlim = c(0, 34))
axis(1, at = c(1:34), labels = names(CampaignsCut.df), las = 2)

# plot centroids
for (i in 1:nrow(km$centers)) {
  lines(km$centers[i, ], lty = i, lwd = 2, col = ifelse(i %in% c(1, 3, 5),
                                                        "black", "dark grey"))
}
